# Generated by Django 4.0 on 2023-05-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListGeneral',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegOrgUnit',
            fields=[
                ('org_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_unit_name', models.CharField(max_length=255)),
                ('parent_org_unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_api.regorgunit')),
            ],
        ),
        migrations.CreateModel(
            name='ListGeo',
            fields=[
                ('geo_id', models.AutoField(primary_key=True, serialize=False)),
                ('geo_name', models.CharField(max_length=255)),
                ('parent_geo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_api.listgeo')),
            ],
        ),
    ]
